default: &default
  tesseract_whitelist: "aäbcdefghijklmnoöpqrsßtuüvwxyzAÄBCDEFGHIJKLMNOÖPQRSTUÜVWXYZ1234567890,/&@.-*€$%!:"

development:
  <<: *default
  url: 'http://172.17.0.4:3000/websocket'
  meteor:
    email: recognizer@getchillbill.com
    password:

production:
  <<: *default
  url: 'https://my.chillbill.co/websocket'
  meteor:
    email: <%= ENV['METEOR_EMAIL'] %>
    password: <%= ENV['METEOR_PASSWORD'] %>
