development:
  url: 'http://localhost:3000/websocket'
  meteor:
    email: recognizer@getchillbill.com
    password: change now!

production:
  url: 'http://chillbill-web.herokuapp.com:80/websocket'
  meteor:
    email: <%= ENV['METEOR_EMAIL'] %>
    password: <%= ENV['METEOR_PASSWORD'] %>
