redis:
  image: redis

rediscli:
  build: .
  dockerfile: Dockerfile-redistools
  links:
    - redis
  command: redis-cli -h redis

sidekiq:
  build: .
  volumes:
    - .:/myapp
  volumes_from:
    - bundle
  links:
    - redis
  env_file: .env
  command: bundle exec sidekiq -r ./sidekiq.rb

processor:
  build: .
  volumes:
    - .:/myapp
  volumes_from:
    - bundle
  links:
    - redis
  env_file: .env
  command: bundle exec rake process

reprocessor:
  build: .
  volumes:
    - .:/myapp
  volumes_from:
    - bundle
  links:
    - redis
  env_file: .env
  command: bundle exec rake reprocess

tests:
  build: .
  volumes:
    - .:/myapp
    - ./tmp/tmpdir:/tmp
  volumes_from:
    - bundle
  env_file: .env-rspec
  environment:
    - MONGO_READ_URL

ml:
  build: .
  volumes:
    - .:/myapp
  volumes_from:
    - bundle
  env_file: .env-ml

# Data container to contain bundled gems
bundle:
  image: busybox
  volumes:
    - /bundle
