redis:
  image: redis
  mem_limit: 200000000

sidekiq:
  image: 175255700812.dkr.ecr.eu-west-1.amazonaws.com/recognizer-repo
  links:
    - redis
  mem_limit: 1000000000
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    RECOGNIZER_ENV: production
    AWS_REGION: eu-central-1
  command: bundle exec sidekiq -r ./sidekiq.rb 2>&1

processor:
  image: 175255700812.dkr.ecr.eu-west-1.amazonaws.com/recognizer-repo
  mem_limit: 200000000
  links:
    - redis
  environment:
    METEOR_EMAIL:
    METEOR_PASSWORD:
    RECOGNIZER_ENV: production
  command: bundle exec rake process 2>&1 | logger -t processor
